### ISSUE TITLE
Ensure coal-sds runs on JDK11

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/coal-sds#32]
Right now there are several issues even starting up basic OODT services when using JDK11
```
lmcgibbn@LMC-056430 /usr/local/coal-sds-deploy/bin $ java -version
java version "11.0.1" 2018-10-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
```
 e.g.
```
Tomcat started.
Workflow Manager started PID file (/usr/local/coal-sds-deploy/workflow/run/cas.workflow.pid).
Resource Manager started PID file (/usr/local/coal-sds-deploy/resmgr/run/cas.resmgr.pid).
Bad level value for property: java.util.logging.FileHandler.level
Bad level value for property: java.util.logging.ConsoleHandler.level
Bad level value for property: .level
Bad level value for property: java.util.logging.FileHandler.level
Bad level value for property: java.util.logging.ConsoleHandler.level
Bad level value for property: .level
Can't set level for java.util.logging.ConsoleHandler
Can't set level for java.util.logging.ConsoleHandler
Can't set level for java.util.logging.FileHandler
Can't set level for java.util.logging.FileHandler
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(DocumentBuilderImpl.java:102)
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:88)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManager.getDocumentRoot(XMLRepositoryManager.java:278)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManager.loadProductTypes(XMLRepositoryManager.java:223)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManager.<init>(XMLRepositoryManager.java:79)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManagerFactory.createRepositoryManager(XMLRepositoryManagerFactory.java:116)
	at org.apache.oodt.cas.filemgr.util.GenericFileManagerObjectFactory.getRepositoryManagerServiceFromFactory(GenericFileManagerObjectFactory.java:125)
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManager.loadConfiguration(XmlRpcFileManager.java:1551)
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManager.<init>(XmlRpcFileManager.java:125)
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManager.main(XmlRpcFileManager.java:1204)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more
Oct 21, 2018 8:05:08 PM org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager loadProperties
INFO: Loading Workflow Manager Configuration Properties from: [/usr/local/coal-sds-deploy/workflow/etc/workflow.properties]
Oct 21, 2018 8:05:08 PM org.apache.oodt.cas.resource.system.XmlRpcResourceManager <init>
INFO: Loading Resource Manager Configuration Properties from: [/usr/local/coal-sds-deploy/resmgr/etc/resource.properties]
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(DocumentBuilderImpl.java:102)
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:88)
	at org.apache.oodt.commons.xml.XMLUtils.getDocumentRoot(XMLUtils.java:190)
	at org.apache.oodt.cas.resource.queuerepo.XmlQueueRepository.loadQueues(XmlQueueRepository.java:91)
	at org.apache.oodt.cas.resource.scheduler.LRUSchedulerFactory.<init>(LRUSchedulerFactory.java:81)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.apache.oodt.cas.resource.util.GenericResourceManagerObjectFactory.getSchedulerServiceFromFactory(GenericResourceManagerObjectFactory.java:361)
	at org.apache.oodt.cas.resource.system.XmlRpcResourceManager.<init>(XmlRpcResourceManager.java:89)
	at org.apache.oodt.cas.resource.system.XmlRpcResourceManager.main(XmlRpcResourceManager.java:446)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 22 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(DocumentBuilderImpl.java:102)
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:88)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepository.getDocumentRoot(XMLWorkflowRepository.java:685)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepository.loadConditions(XMLWorkflowRepository.java:496)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepository.<init>(XMLWorkflowRepository.java:122)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepositoryFactory.createRepository(XMLWorkflowRepositoryFactory.java:106)
	at org.apache.oodt.cas.workflow.util.GenericWorkflowObjectFactory.getWorkflowRepositoryFromClassName(GenericWorkflowObjectFactory.java:103)
	at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager.getWorkflowRepositoryFromProperty(XmlRpcWorkflowManager.java:677)
	at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager.<init>(XmlRpcWorkflowManager.java:86)
	at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager.main(XmlRpcWorkflowManager.java:649)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more
Using CATALINA_BASE:   /usr/local/coal-sds-deploy/tomcat
Using CATALINA_HOME:   /usr/local/coal-sds-deploy/tomcat
Using CATALINA_TMPDIR: /usr/local/coal-sds-deploy/tomcat/temp
Using JRE_HOME:        /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Using CLASSPATH:       /usr/local/coal-sds-deploy/tomcat/bin/bootstrap.jar:/usr/local/coal-sds-deploy/tomcat/bin/tomcat-juli.jar
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
PID file (/usr/local/coal-sds-deploy/resmgr/run/cas.resmgr.pid) found but no matching process was found. Stop aborted.
PID file (/usr/local/coal-sds-deploy/workflow/run/cas.workflow.pid) found but no matching process was found. Stop aborted.
Tomcat started.
Resource Manager started PID file (/usr/local/coal-sds-deploy/resmgr/run/cas.resmgr.pid).
Workflow Manager started PID file (/usr/local/coal-sds-deploy/workflow/run/cas.workflow.pid).
Bad level value for property: java.util.logging.FileHandler.level
Bad level value for property: java.util.logging.ConsoleHandler.level
Bad level value for property: .level
Bad level value for property: java.util.logging.FileHandler.level
Bad level value for property: java.util.logging.ConsoleHandler.level
Bad level value for property: .level
Can't set level for java.util.logging.ConsoleHandler
Can't set level for java.util.logging.FileHandler
Can't set level for java.util.logging.ConsoleHandler
Can't set level for java.util.logging.FileHandler
Oct 21, 2018 8:06:13 PM org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager loadProperties
INFO: Loading Workflow Manager Configuration Properties from: [/usr/local/coal-sds-deploy/workflow/etc/workflow.properties]
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(DocumentBuilderImpl.java:102)
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:88)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManager.getDocumentRoot(XMLRepositoryManager.java:278)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManager.loadProductTypes(XMLRepositoryManager.java:223)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManager.<init>(XMLRepositoryManager.java:79)
	at org.apache.oodt.cas.filemgr.repository.XMLRepositoryManagerFactory.createRepositoryManager(XMLRepositoryManagerFactory.java:116)
	at org.apache.oodt.cas.filemgr.util.GenericFileManagerObjectFactory.getRepositoryManagerServiceFromFactory(GenericFileManagerObjectFactory.java:125)
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManager.loadConfiguration(XmlRpcFileManager.java:1551)
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManager.<init>(XmlRpcFileManager.java:125)
	at org.apache.oodt.cas.filemgr.system.XmlRpcFileManager.main(XmlRpcFileManager.java:1204)
Oct 21, 2018 8:06:13 PM org.apache.oodt.cas.resource.system.XmlRpcResourceManager <init>
INFO: Loading Resource Manager Configuration Properties from: [/usr/local/coal-sds-deploy/resmgr/etc/resource.properties]
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(DocumentBuilderImpl.java:102)
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:88)
	at org.apache.oodt.commons.xml.XMLUtils.getDocumentRoot(XMLUtils.java:190)
	at org.apache.oodt.cas.resource.queuerepo.XmlQueueRepository.loadQueues(XmlQueueRepository.java:91)
	at org.apache.oodt.cas.resource.scheduler.LRUSchedulerFactory.<init>(LRUSchedulerFactory.java:81)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at org.apache.oodt.cas.resource.util.GenericResourceManagerObjectFactory.getSchedulerServiceFromFactory(GenericResourceManagerObjectFactory.java:361)
	at org.apache.oodt.cas.resource.system.XmlRpcResourceManager.<init>(XmlRpcResourceManager.java:89)
	at org.apache.oodt.cas.resource.system.XmlRpcResourceManager.main(XmlRpcResourceManager.java:446)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 22 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/dom/ls/DocumentLS
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.<init>(DocumentBuilderImpl.java:102)
	at org.apache.xerces.jaxp.DocumentBuilderFactoryImpl.newDocumentBuilder(DocumentBuilderFactoryImpl.java:88)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepository.getDocumentRoot(XMLWorkflowRepository.java:685)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepository.loadConditions(XMLWorkflowRepository.java:496)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepository.<init>(XMLWorkflowRepository.java:122)
	at org.apache.oodt.cas.workflow.repository.XMLWorkflowRepositoryFactory.createRepository(XMLWorkflowRepositoryFactory.java:106)
	at org.apache.oodt.cas.workflow.util.GenericWorkflowObjectFactory.getWorkflowRepositoryFromClassName(GenericWorkflowObjectFactory.java:103)
	at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager.getWorkflowRepositoryFromProperty(XmlRpcWorkflowManager.java:677)
	at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager.<init>(XmlRpcWorkflowManager.java:86)
	at org.apache.oodt.cas.workflow.system.XmlRpcWorkflowManager.main(XmlRpcWorkflowManager.java:649)
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ls.DocumentLS
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 19 more
Tomcat started.
PID file (/usr/local/coal-sds-deploy/filemgr/run/cas.filemgr.pid) found. Is File Manager still running? Start aborted.
PID file (/usr/local/coal-sds-deploy/workflow/run/cas.workflow.pid) found. Is Workflow Manager still running? Start aborted.
PID file (/usr/local/coal-sds-deploy/resmgr/run/cas.resmgr.pid) found. Is Resource Manager still running? Start aborted.
Using CATALINA_BASE:   /usr/local/coal-sds-deploy/tomcat
Using CATALINA_HOME:   /usr/local/coal-sds-deploy/tomcat
Using CATALINA_TMPDIR: /usr/local/coal-sds-deploy/tomcat/temp
Using JRE_HOME:        /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home
Using CLASSPATH:       /usr/local/coal-sds-deploy/tomcat/bin/bootstrap.jar:/usr/local/coal-sds-deploy/tomcat/bin/tomcat-juli.jar
PID file (/usr/local/coal-sds-deploy/workflow/run/cas.workflow.pid) found but no matching process was found. Stop aborted.
NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
PID file (/usr/local/coal-sds-deploy/resmgr/run/cas.resmgr.pid) found but no matching process was found. Stop aborted.
ID file (/usr/local/coal-sds-deploy/filemgr/run/cas.filemgr.pid) found with PID 10541 but no matching process was found. Removed /usr/local/coal-sds-deploy/filemgr/run/cas.filemgr.pid, now FileManager can be started.
```

**Comment by lewismc** [comment]
Fix https://github.com/capstone-coal/coal-sds/commit/8876c3460090eb5f9379eb150f44101048958121
